% Auto generated function to compile/launch ModelSim simulator
% 
% Generated by MATLAB 24.2 and HDL Coder 24.2

function launch_cordicfsm_fixpt_cosim
% Make sure there is no HDL simulator using the communication channel
pid = pingHdlSim(1);
if pid > 0
   error('hdlverifier:mlhdlc:HDLServerExist','Another instance of HDL simulator exists. Close all HDL simulator instances and try again');
end
currentdir = cd('D:\Matlab\W_exports\cordicfsm\codegen\cordicfsm\hdlsrc');
onCleanupObj = onCleanup(@() cd(currentdir));
% Pre-sim TCL commands
tclCmds = { ...
    'vlib work',...% Compile the generated code
    'vcom cordicfsm_fixpt_pac.vhd',...
    'vcom cordicfsm_fixpt.vhd',...
    'vsimmatlabsysobj -voptargs=+acc work.cordicfsm_fixpt',...% Initiate cosimulation
    'set UserTimeUnit ns',...% Set simulation time unit
    'puts ""',...
    'puts "Ready for cosimulation..."',...
};
% Launch HDL simulator
vsim('tclstart',tclCmds,'runmode','Batch');

% Wait for HDL simulator to ready
disp('### Waiting for ModelSim to start ');
pingHdlSim(180);

