% Function localRecompile_cordicfsm_wrapper_fixpt_cosim recreates a MEX-function cordicfsm_wrapper_fixpt_cosim_mex from MATLAB function cordicfsm_wrapper_fixpt_cosim
% Generated by MATLAB 24.2 and HDL Coder 24.2
function localRecompile_cordicfsm_wrapper_fixpt_cosim

load('D:\Matlab\W_exports\cordicfsm\codegen\cordicfsm\cosim\localCodegenArgs_cordicfsm_wrapper_fixpt_cosim');

fxptPath = 'D:\Matlab\W_exports\cordicfsm\codegen\cordicfsm\fixpt';
addpath(fxptPath);
cleanupObj = onCleanup(@() rmpath(fxptPath));
codegen -args exInputs -o 'D:\Matlab\W_exports\cordicfsm\codegen\cordicfsm\cosim\cordicfsm_wrapper_fixpt_cosim_mex' cordicfsm_wrapper_fixpt_cosim;

