% Auto generated function to execute the generated cosimulation test bench
% 
% Generated by MATLAB 24.2 and HDL Coder 24.2

function run_cordicfsm_fixpt_cosim

% Launch HDL simulator
disp('### Launching ModelSim for cosimulation ');
launch_cordicfsm_fixpt_cosim;

% Clear persistent variables before simulation
l_clearPersistentVariable;

% Clear persistent variables after simulation
onCleanupObj = onCleanup(@() l_clearPersistentVariable);

% Add current working directory to search path
savedPathVar = addpath(pwd);
restorePathObj = onCleanup(@() path(savedPathVar));

% Run generated test bench
disp('### Simulating generated test bench ');
% Exercise the compiled version of cordicfsm_wrapper_fixpt_cosim in the generated test bench.
% To debug the test bench with the original function "cordicfsm_wrapper_fixpt_cosim",
% replace the next line with "test_cordicfsm_cosim"
coder.runTest('localRunTest_cordicfsm_fixpt','cordicfsm_wrapper_fixpt_cosim');
% To recompile MATLAB function "cordicfsm_wrapper_fixpt_cosim",
% run the re-compilation function "localRecompile_cordicfsm_wrapper_fixpt_cosim".
disp('### Finished Simulation');

end

function l_clearPersistentVariable
% Clear reference DUT function
clear cordicfsm_fixpt;

% Clear cosimulation System object wrapper function
clear cordicfsm_fixpt_sysobj_cosim;

% Clear cosimulation function
clear cordicfsm_fixpt_cosim;

% Clear generated MEX function
clear cordicfsm_wrapper_fixpt_cosim_mex

end

