-- -------------------------------------------------------------
-- 
-- File Name: D:\Matlab\W_exports\cordicfsm\codegen\cordicfsm\hdlsrc\cordicfsm_fixpt_pac.vhd
-- Created: 2024-12-22 19:58:12
-- 
-- Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE cordicfsm_fixpt_pac IS
  TYPE vector_of_unsigned14 IS ARRAY (NATURAL RANGE <>) OF unsigned(13 DOWNTO 0);
END cordicfsm_fixpt_pac;

